### ISSUE TITLE
JSON Literals not supported via @json KEYWORD

### ISSUE THREAD

**Issue by zwelz3** [digitalbazaar/pyld#100]
The [JSON-LD 1.1 Spec has support for JSON Literals](https://w3c.github.io/json-ld-syntax/#json-literals). 

The pyld processor does not have support for this keyword, and returns the error 
> JsonLdError: ('Invalid JSON-LD syntax; an @context @type value must be an absolute IRI.',)
Type: jsonld.SyntaxError
Code: invalid type mapping

This minimal example from the spec recreates the error:
```
from pyld.jsonld import expand

document = expand(
  {
    "@context": {
      "@version": 1.1,
      "e": {"@id": "http://example.com/vocab/json", "@type": "@json"}
    },
    "e": [  ]
  }
)
```

**Comment by davidlehn** [comment]
Should now be fixed in 2.0.0.
