### ISSUE TITLE
no term-to-IRI expansion

### ISSUE THREAD

**Issue by mfrigerio17** [digitalbazaar/pyld#130]
Hi, I am new to JSON-LD so please excuse me if the question does not make much sense.
Consider the following:

```python
import json
from pyld import jsonld

c = jsonld.compact( {'key':'value'}, {'key':'http://whatever.org/key'} )
print(c)  # {'@context': {'key': 'http://whatever.org/key'}} ## 'key':'value' is gone
```
```python
c = jsonld.compact( {'http://whatever.org/key':'value'}, {'key':'http://whatever.org/key'} )
print(c)  #{'@context': {'key': 'http://whatever.org/key'}, 'key': 'value'}
```
In the first snippet, `key` is not matched with the term in the given context.

Why do I have to write the full IRI (`'http://whatever.org/key'`) explicitly _in the document_ ??
That kind of voids one of the advantages of having a context, doesn't it?

I think this behaviour is not consistent with the JSON-LD playground, where the first example would result in a compacted document which includes the term `key:value`. See [here](https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%7B%22%40context%22%3A%7B%22key%22%3A%22http%3A%2F%2Fwhatever.org%2Fkey%22%7D%2C%22key%22%3A%22value%22%7D&context=%7B%7D)
The specs say "Term-to-IRI expansion occurs if the key matches a term defined within the active context", but that does not seem to be happening in PyLD (see [example 11 of the specs](https://w3c.github.io/json-ld-syntax/#example-11-term-expansion-from-context-definition))

Thank you

**Comment by davidlehn** [comment]
The `compact()` call is compacting JSON-LD data with a new context.  Effectively it will call `expand()` on the input data and then run the compaction algorithm with the new context.  When `{'key': 'value'}` is expanded, it doesn't know what `key` is so the output is empty.  It then compacts empty data which results in empty output.

```py
e = jsonld.expand( {'key':'value'} )
print(e) # []
```

The choices here are to make the input valid by either adding the context or use the `expandContext` option.  These will allow the input to be understood when compacting.

```py
# add context to input
ctx = {'key':'http://whatever.org/key'}
c = jsonld.compact( {'@context': ctx, 'key':'value'}, ctx )
print(c)  # {'@context': {'key': 'http://whatever.org/key'}, 'key': 'value'}

# use expandContext option
ctx = {'key':'http://whatever.org/key'}
c = jsonld.compact( {'key':'value'}, ctx, {'expandContext': ctx} )
print(c)  # {'@context': {'key': 'http://whatever.org/key'}, 'key': 'value'}
```

The use case for compacting with the same context as the input is usually to convert full URLs to shorter terms. 
 But when using different contexts, you can change the names as needed.

```py
# use expandContext option
ctx1 = {'key':'http://whatever.org/key'}
ctx2 = {'altKeyName':'http://whatever.org/key'}
c = jsonld.compact( {'@context': ctx1, 'key':'value'}, ctx2 )
print(c)  # {'@context': {'altKeyName': 'http://whatever.org/key'}, 'altKeyName': 'value'}
```

**Comment by mfrigerio17** [comment]
Hi @davidlehn , thanks for your reply.
I understand what you are saying, and your examples.

I think I misunderstood the purpose of compacting. My target is to process the json-ld document to expand all the keys, remove the context, and be left with unambiguous (because the keys are IRIs) json (not LD). That seems to be the purpose of *expansion*, although expansion introduces all those unnecessary arrays `[]`...

Still, the compaction in the playground does exactly what I want (hence my confusion), by turning
```
{
  "@context": {
    "key" : "http://whatever.org/key"
  },
  "key" : "value"
}
```
into
```
{
  "http://whatever.org/key": "value"
}
```
which is the same as expansion, but without unnecessary arrays. This is not achievable with the PyLD API, I suppose.
Is it a non-standard thing of the playground, perhaps?

PS.: for the convenience of the reader, here is the expanded doc:
```
[
  {
    "http://whatever.org/key": [
      {
        "@value": "value"
      }
    ]
  }
]
```

**Comment by davidlehn** [comment]
Perhaps you want to compact with an empty context `{}`?  You'll still need to ensure the input data is understood by having a context in it or using the `expandContext` option.

Depending on your data and options used this might cause some undesired changes.  Specifically related to arrays being used or not used (but there are other cases).  There is a `compactArrays` option, but that effects everything and doesn't have a "preserve" sort of mode.  I'm not sure if there's an easy way to do that.

**Comment by mfrigerio17** [comment]
Thanks, using the empty context does what I want.
Now I realize that that is also the case in the playground. Sorry about it, I overlooked the `{}` in the right pane.

I'll keep an eye for undesired side effects.
