### ISSUE TITLE
Compact a framed JSON-LD document?

### ISSUE THREAD

**Issue by stefanbischof** [digitalbazaar/pyld#168]
Hi,

is it possible to compact a framed JSON-LD document?

I'd like to convert a JSON-LD document to a nice, framed JSON document (with the context in the HTTP header). Having the complete IRIs again in the framed output kinda defeats the purpose.

Compacting via `compact()` works fine, also framing via the `frame()` function works. But when I first compact the JSON-LD document and frame it, it is again expanded. I found no option to prevent `frame()` to expand the document again. Is this possible with pyLD?

**Comment by stefanbischof** [comment]
Found the solution: adding the context to the frame does exactly what I wanted.

**Comment by Natureshadow** [comment]
@stefanbischof Can you share your code, please? I am facing the same issue – I want all keys in my JSON-LD to be as short as possible, and all IRI prefixes added to the `@context`.

Currently, I am doing:

```python
profile = "https://www.w3.org/ns/activitystreams"

doc = json.loads(graph.serialize(format="json-ld"))
# graph is and rdflib Graph, and at this point, `@context` in `doc` contains all prefixes

        framed = jsonld.frame(doc, profile, options={"embed": "@always"})
        compacted = jsonld.compact(framed, profile)
```

How would I ge tit to add more, or even all, prefixes to the `@context` of the final document, and shorten all keys?
