### ISSUE TITLE
framing algorithm embedding options

### ISSUE THREAD

**Issue by faassen** [digitalbazaar/pyld#38]
I only faintly understand how framing works, but from my reading of the discussion here:

https://github.com/digitalbazaar/jsonld.js/pull/68

there are three embed options, `@never`, `@once` and `@always`. But in the pyld sources I can see `@last` instead of `@once`. Isn't that inconsistent with the latest state of jsonld.js?

**Comment by dlongley** [comment]
> Isn't that inconsistent with the latest state of jsonld.js?

No, ```@once``` was renamed to ```@last``` to better reflect which occurrence in the data is the one that gets embedded (it's the last one). See https://github.com/json-ld/json-ld.org/issues/377 and https://github.com/digitalbazaar/jsonld.js/blob/master/js/jsonld.js#L451.

**Comment by faassen** [comment]
Ah, I somehow was under the mistaken impression that it `@last` became `@once`, sorry! Thank you for your continued patience with my noob questions!

**Comment by dlongley** [comment]
:)
