### ISSUE TITLE
README.md  - incorrect json example output

### ISSUE THREAD

**Issue by lexruee** [digitalbazaar/pyld#40]
The example output of an expanded document is not correct.

According the readme the output is a dictionary:
```python
print(json.dumps(expanded, indent=2))
# Output:
# {
#   "http://schema.org/image": [{"@id": "http://manu.sporny.org/images/manu.png"}],
#   "http://schema.org/name": [{"@value": "Manu Sporny"}],
#   "http://schema.org/url": [{"@id": "http://manu.sporny.org/"}]
# }
```

I guess this should be changed to:
```python
print(json.dumps(expanded, indent=2))
# Output:
# [ {
#   "http://schema.org/image": [{"@id": "http://manu.sporny.org/images/manu.png"}],
#   "http://schema.org/name": [{"@value": "Manu Sporny"}],
#   "http://schema.org/url": [{"@id": "http://manu.sporny.org/"}]
# } ]
```

**Comment by davidlehn** [comment]
Fixed.
https://github.com/digitalbazaar/pyld/commit/b2cc497eedfc8cf712230ae0066c3bcab9108f4b

**Comment by sohkai** [comment]
@davidlehn I came across this recently and was curious: is there a reason why it comes out as a list and not just a dict? Seems like a weird difference between PyLD and jsonld.js
