### ISSUE TITLE
Difference between behavior of jsonls.js on Playground and pyld

### ISSUE THREAD

**Issue by mtpain** [digitalbazaar/pyld#43]
I've run into an issue where I get a different result from `pyld` that's different from what the JSON-LD playground produces.

On the JSON-LD playground I changed the "Event" example to this:

```json
{
  "@context": {
    "ical": "http://www.w3.org/2002/12/cal/ical#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "ical:dtstart": {
      "@type": "xsd:dateTime"
    }
  },
  "ical": "Lady Gaga Concert",
  "ical:location": "New Orleans Arena, New Orleans, Louisiana, USA",
  "ical:dtstart": "2011-04-09T20:00Z"
}
```

And the compact result is

```json
{
  "@context": {
    "ical": "http://www.w3.org/2002/12/cal/ical#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "ical:dtstart": {
      "@type": "xsd:dateTime"
    }
  },
  "ical": "Lady Gaga Concert",
  "ical:dtstart": "2011-04-09T20:00Z",
  "ical:location": "New Orleans Arena, New Orleans, Louisiana, USA"
}
```

However in Python 2.7.10

```python
from pyld import jsonld
import json

doc =  {  "ical": "Lady Gaga Concert", "ical:dtstart": "2011-04-09T20:00Z",  "ical:location": "New Orleans Arena, New Orleans, Louisiana, USA"}

context = {"ical": "http://www.w3.org/2002/12/cal/ical#",  "xsd": "http://www.w3.org/2001/XMLSchema#",    "ical:dtstart": { "@type": "xsd:dateTime"}}

print json.dumps(jsonld.compact(doc, context))
```
prints
```json
{
  "@context": {
    "ical:dtstart": {
      "@type": "xsd:dateTime"
    },
    "ical": "http://www.w3.org/2002/12/cal/ical#",
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  },
  "ical:location": "New Orleans Arena, New Orleans, Louisiana, USA",
  "ical:dtstart": "2011-04-09T20:00Z"
}
```
The `"ical": "Lady Gaga Concert",` line is now missing.

This may seem pointless, but I am developing "normalized" metadata where I want the synonyms from different vocabularies to be used interchangeably, and I want this to happen at the context level, for example,

```python
doc = dict(start_datetime='2014-01-01T13:00:00', ...)
context_one = dict(start_datetime='http://vocabulary-one.com/start_date', ...)
context_two = dict(start_datetime='http://vocabulary-two.com/coverage_start_datetime', ...)
``` 

Then depending on which context is used, different linked data is produced.  Is there perhaps an alternative, more correct way of approaching this?

**Comment by dlongley** [comment]
The inputs are different. The input you're providing to the playground includes an `@context` which allows the processor to interpret the data. The input you're providing to pyld doesn't have any `@context` so the processor drops the "ical" property (it has no mapping) and it interprets the other properties as full URIs with the "ical" scheme (not CURIEs) and keeps them.

Instead, provide a context along with your input. You can do this either by injecting an `@context` property into the input, or you may use the `expandContext` option in the API:

```python
jsonld.compact(doc, context, {'expandContext': context});
```

Note that compaction is typically used to convert a document from one context to a different one, but here you're compacting to the same context. Depending on your use case, you may just be able to attach an `@context` property to the dictionary and be done. If you do really require some processing to be done, however, the above seems to be what you're looking for.

**Comment by mtpain** [comment]
Ok, thanks for your quick reply.  It's a little confusing for me, I was expecting the second argument to `compact`, described as "the JSON-LD context to compact with" in the docstring, to be identical to the `@context` field of a JSON-LD document.  In other words, it's strange to me that one has to pass `context` twice to get the context to work like in the jsonld.org examples.  But then again I'm pretty ignorant of what common use cases of JSON-LD are, so maybe that's why it doesn't make sense to me.

In any case, this gives me something I can work with, thanks again!
