### ISSUE TITLE
Exception handling error

### ISSUE THREAD

**Issue by hsolbrig** [digitalbazaar/pyld#45]
Line 4465 of jsonld.py (JsonLdError.__str__) reads "rval = repr(self.message)".  The Exception class doesn't have a 'message' attribute so this throws a second exception.  Changing the line to "rval = repr(self)" seems to solve the problem.

**Comment by davidlehn** [comment]
Thanks for the report.  Fixed and released 0.7.0.  Used `str(self.args)` which seems to be in line with what was there before.
