### ISSUE TITLE
JSON-LD 1.1

### ISSUE THREAD

**Issue by kevinxin90** [digitalbazaar/pyld#58]
Hi,

I'm wondering is there any plan to make the PyLD compatible with the current JSON-LD version 1.1.

Thanks!

**Comment by dlongley** [comment]
PyLD will eventually implement JSON-LD 1.1. We don't have a timeline yet for moving it forward, but PRs are always welcome if there's interest in speeding up the process.

**Comment by azaroth42** [comment]
See: https://github.com/digitalbazaar/pyld/tree/json-ld-1.1  :)

**Comment by davidlehn** [comment]
1.0.1 has been released with JSON-LD 1.1 draft spec support.
