### ISSUE TITLE
Pypi package does not installs - require requests

### ISSUE THREAD

**Issue by frague59** [digitalbazaar/pyld#68]
Hi, 

I'm installing PyLD into a (almost empty) docker container, for a django project.

I've added PyLD into a requirement file, and I've the following error when installing the requirements: 

```python 
...
Collecting PyLD (from -r requirements/common.txt (line 42))
  Downloading PyLD-0.8.0.tar.gz (44kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0b391b8m/PyLD/setup.py", line 17, in <module>
        from pyld import jsonld
      File "/tmp/pip-build-0b391b8m/PyLD/lib/pyld/__init__.py", line 2, in <module>
        from . import jsonld
      File "/tmp/pip-build-0b391b8m/PyLD/lib/pyld/jsonld.py", line 19, in <module>
        import requests
    ImportError: No module named 'requests'
```
Looking in the setup.py file, I can see at line 17:
```python 
from pyld import jsonld
```
where an attempt to load the current installing module, which needs requests, which is not installled because it is a requirement of the current installing module...

I think you shouldn't try to load the _currently installing_ module, the setup.py file is used both to create the package (sdist) and install it.

Thanks for upgrading the pypi package !

**Comment by yarikoptic** [comment]
yeap -- can only confirm that this release broke our @datalad CI setup all around
```shell
$> venvs-pyld/bin/pip install pyld                    
Collecting pyld
  Using cached PyLD-0.8.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-cxFBqw/pyld/setup.py", line 17, in <module>
        from pyld import jsonld
      File "/tmp/pip-build-cxFBqw/pyld/lib/pyld/__init__.py", line 2, in <module>
        from . import jsonld
      File "/tmp/pip-build-cxFBqw/pyld/lib/pyld/jsonld.py", line 19, in <module>
        import requests
    ImportError: No module named requests
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-cxFBqw/pyld/
```
I would appreciate a quick bugfix release.  Thanks very much in advance, let me know if you need assistance

**Comment by kimdhamilton** [comment]
This is affecting us as well: https://github.com/blockchain-certificates/cert-issuer/issues/71

I confirmed that forking pyld, changing:
`from . import jsonld`
to 
`from pyld import jsonld`

And publishing (not as pyld, don't worry) fixed my callers. (My commit has other details because I build differently; the only one that matters should be __init__.py)
https://github.com/blockchain-certificates/pyld/commit/6d02c09d5c3ec4d67f268c1e7363324a41c2a536

If you guys expect to have a fix soon (today-ish) I'll wait. Otherwise, I'll use my forked version and patch it up when your fix is available.

**Comment by kimdhamilton** [comment]
Confirmed in my minimal repro. https://travis-ci.org/kimdhamilton/pyld-test

Thanks @davidlehn!

**Comment by yarikoptic** [comment]
Thanks @davidlehn indeed!
Cheers
