### ISSUE TITLE
couldn't API stay compatible in 0.8.x?

### ISSUE THREAD

**Issue by yarikoptic** [digitalbazaar/pyld#69]
just a question:  couldn't there remain some  `load_document` adapter to use flashy new `requests_document_loader` so projects using previous API could still use it? (sorry -- I didn't look in detail inside etc to see if that is feasible or not, decided just to ask)

**Comment by davidlehn** [comment]
Ok.  I just released 0.8.2 that adds back the `load_document` API.  It just sets it to the default document loader, which is now based on requests.  I think since API is just `f(url)` it should work.  Please test and report if it works or not.

**Comment by yarikoptic** [comment]
Seems (according to local tests, travis yet to run) to be all kosher again, thanks @davidlehn !

**Comment by yarikoptic** [comment]
Fixed in 9b3fb90
