### ISSUE TITLE
The JsonLdProcessor.parse_nquads method fails to parse an nquad line with an uppercase region subtag

### ISSUE THREAD

**Issue by apeters** [digitalbazaar/pyld#86]
For example this nquad line will fail to parse
```
'<http://www.test.org> <http://purl.org/dc/terms/identifier> "http://www.test.org/id1"@en-US <http://test.org/test> .'
```

notice the use of `@en-US` 
the line will parse just fine if `@en-us` is used

generally, it seems that the region subtag (the `US` part) is usually displayed as uppercase.
see: https://www.w3.org/International/articles/language-tags/#region

But more importantly, the case of the entire language tag should be ignored (at least as far as parsing is concerned).

Per: https://tools.ietf.org/html/rfc5646#section-2.1.1
```
 At all times, language tags and their subtags, including private use
 and extensions, are to be treated as case insensitive: there exist
 conventions for the capitalization of some of the subtags, but these
 MUST NOT be taken to carry meaning.
```

**Comment by davidlehn** [comment]
1.0.4 released with #87.
